### ISSUE TITLE
[Bug]: Add Image makes function random changes to image

### ISSUE THREAD

**Issue by Softbox44** [Stirling-Tools/Stirling-PDF#2246]
### Installation Method

Docker

### The Problem

**Actions taken:**

- Uploading PDF file
- Uploading image
- Moving image to a specific location on the PDF
- Saving PDF (incl Image)

**Problem after saving the PDF** > The image inside the saved PDF appears on a completely different location, 90 degrees rotated to the left.

### Version of Stirling-PDF

0.33.2

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
I believe this is a bug for PDFs generated from Google docs
I couldn't figure out cause 
Welcome to have others investigate

**Comment by thisisrenan** [comment]
Hi @Softbox44, I couldn't replicate your problem. Could you provide more details about how it occurs? Which version of Docker are you using?

**Comment by Frooodle** [comment]
Did you try it with a google doc btw?

**Comment by thisisrenan** [comment]
> Did you try it with a google doc btw?

Yes, the error did not occur for me.

**Comment by Softbox44** [comment]
Hi - has this been fixed or do you still require more input from me?

**Comment by Frooodle** [comment]
Should be fixed in latest version 0.33.2

**Comment by Softbox44** [comment]
not fixed in 0.39.0

**Comment by Softbox44** [comment]
and i am not using google docs.

**Comment by thisisrenan** [comment]
I'll take a look, @Softbox44 does the problem still occur the same way?

**Comment by Softbox44** [comment]
Yes. Exactly the same.
