### ISSUE TITLE
[Bug]: App does not accept local URL

### ISSUE THREAD

**Issue by merlin260880** [Stirling-Tools/Stirling-PDF#5059]
### Installation Method

Docker

### The Problem

I updated the docker container to latest 2.01 version.
Then After first access through web GUI I get the information for an application for Windows.
Then I downloaded it.
Now when I want to enter the same URL as I use within the webbrowser, I got the message "Connection to the server could not be established".
See

<img width="587" height="463" alt="Image" src="https://github.com/user-attachments/assets/20160db3-46d4-40df-bf41-510ba491492a" />

### Version of Stirling-PDF

2.0.1

### Last Working Version of Stirling-PDF

2.0.1

### Page Where the Problem Occurred

within the Windows App

### Docker Configuration

```txt

```

### Relevant Log Output

```txt

```

### No Duplicate of the Issue

- [x] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
Currently our desktop app only connects to a server with login enabled, is that the case here?

**Comment by merlin260880** [comment]
Hi thanks for the fast reply.
I have login enabled to request a password, see below under security settings.
Do you mean that?

<img width="679" height="207" alt="Image" src="https://github.com/user-attachments/assets/670cf2d9-c448-420a-83cf-296d438df254" />

**Comment by Frooodle** [comment]
Correct enabling that and then restarting server should then set your credentials 
After a login via webui it should then let you login to server etc in app

**Comment by merlin260880** [comment]
I am sorry to say, but this was already enabled.

**Comment by Frooodle** [comment]
Damm, we had a few others report similar
We are investigating but not been able to reproduce it currently

**Comment by merlin260880** [comment]
I am not so deep within docker and I used it with portainer to setup, but if I can help you just let me know. But I think it is from the application, which does not accept it.

**Comment by merlin260880** [comment]
Within the docker logfiles I do not see any message, related to that issue.

**Comment by mgnv7** [comment]
Hi, 

I am another self-hoster with the same issue. Login enabled in the yml file and credentials configured. Cannot connect to local server via url:

<img width="658" height="272" alt="Image" src="https://github.com/user-attachments/assets/29cd78b1-36a8-4db6-90fd-0cee9c80bbc9" />

<img width="573" height="441" alt="Image" src="https://github.com/user-attachments/assets/eeb8d504-886b-4b83-889c-094505cbe556" />

**Comment by Frooodle** [comment]
Canyou access your servers
endpoint /api/v1/info/status

such as
http://localhost:8080/api/v1/info/status

**Comment by Frooodle** [comment]
I'm wondering if it's a operating system firewall issue

**Comment by mgnv7** [comment]
No Issues with the firewall. I am able to connect to it via browser without any problem. I can also connect to the port 8080 via CLI as well. e.g Telnet & nmap.

<img width="514" height="138" alt="Image" src="https://github.com/user-attachments/assets/e765c48e-f4d2-411e-a49a-a3f3afaba31b" />

**Comment by mgnv7** [comment]
I did some troubleshooting.

Started packet capture on my local PC via Wireshark and used tcpdump on my Portainer server filtered on port 8080. 

>Tested connection from my PC to PDF-Stirling local server URL, no packets were captured.
>Tested using browser, immediately saw packets sent from my PC and packets received in my Portainer server.

This tells me that the PDF-Stirling application isn't sending the request to the local server. Maybe something in the code?

**Comment by Frooodle** [comment]
Appreciate the extra investigation! That's really helpful

**Comment by merlin260880** [comment]
Sorry for late reply, was short shopping.
I tried same at my side with the API, also get the same.

<img width="270" height="67" alt="Image" src="https://github.com/user-attachments/assets/17fd939c-6bed-46e3-904a-afdd7bcc28e9" />

Thanks mgnv7 for your investigation

**Comment by Frooodle** [comment]
We made a test installer which fixes a few bugs, is anyone on a windows machine that can test this it would be appreciated
https://github.com/Stirling-Tools/Stirling-PDF/releases/download/v2.0.1/Stirling-PDF_2.0.0_x64_en-US-test-dontuse.msi

Since the error cant be reproduced on our side its been hard for us to test

**Comment by merlin260880** [comment]
Sorry to say, still the same issue.
When you can programme something with logfiles, I can return them to you.

**Comment by Frooodle** [comment]
Damm worth a try, appreciate you checking

**Comment by Frooodle** [comment]
Found the issue! will have a fix today or tomororw out! thanks for all your help

**Comment by rogerineugene-svg** [comment]
Damn.   Brand new install, thought I'd try it out.   Running server via docker on home network.   Installed the windows client.  got the same exact error message.  api/v1/info/status  yields:   2.0.1 status "up".

Glad there's a fix in the works.  
since it's my home network, I was running without SSL.  Thought that might be the problem, so installed NGINX on the pi, same results.

Finally figured I'd check for issues.

**Comment by Frooodle** [comment]
Okay hopefully resolved in 2.0.2?

**Comment by rogerineugene-svg** [comment]
Worked for me. 
2.0.2

**Comment by merlin260880** [comment]
Hi Frooodle

Thanks for your awesome tool!
At my side it works also now...

**Comment by bahree** [comment]
Sorry but where do we get the 2.0.2 version? The release still doesn't link to that - would also be helpful to have the version number in the MSI or the start of the installer.

**Comment by balazs-szucs** [comment]
Hi @bahree,

Every release is in: https://github.com/Stirling-Tools/Stirling-PDF/releases 

Click on the "Assets" dropdown menu (at the bottom of each release), and you can choose what to download there.

The release links to that, but to double-check you see what it downloads from the URL:

<img width="1913" height="847" alt="Image" src="https://github.com/user-attachments/assets/9b94d7d8-0d9b-43b9-977f-767e917ce460" />

**Comment by bahree** [comment]
Thanks  I got the latest version of the windows app (2.1.0) which was released yesterday and I still see this issue on that where the windows app cannot connect to the server. I was then asking in case it was a different forked version. The thread talks about this being fixed in `2.0.2` - was it not pulled into the latest version? @Frooodle would we need to relook at this?

<img width="895" height="747" alt="Image" src="https://github.com/user-attachments/assets/d57ae2fe-0484-4395-a1a1-0579d63104af" />

**Comment by Frooodle** [comment]
There seems to be a cache issue with the desktop version 
It might be you need to uninstall then reinstall instead of installing ontop 

Another option is also to clear your appdata/Stirling pdf folder 
We are working to address this as it's caused us other issues as well

**Comment by bahree** [comment]
I did uninstall and reinstall -- each time so that didn't work. 

Clear the appdata/ also did not work unfortunately. 

I saw the following two areas in case anyone else is looking at this too.
- `AppData\Local\stirling.pdf.dev`
- `AppData\Roaming\Stirling-PDF`

**Comment by Frooodle** [comment]
Damm :(

**Comment by bahree** [comment]
Sorry one more data point - and I double checked that I was getting 2.1.0 -- but when I isntall it, in windows I still see v2.0.0 - I don't know if that is the wrong msi so a asset issue, or if it is really is 2.1.0, but the code / resource string or whatever isn't updated.

<img width="227" height="84" alt="Image" src="https://github.com/user-attachments/assets/1204ffb4-a491-4939-be97-4e917f792d9d" />
